### ISSUE TITLE
Interpolation error on 'S'

### ISSUE THREAD

**Issue by davelab6** [itfoundry/roundo#1]
![screen shot 2016-01-05 at 16 12 13](https://cloud.githubusercontent.com/assets/261579/12127789/268ea8a4-b3c7-11e5-86d8-bb98fd299e4d.png)
![screen shot 2016-01-05 at 16 12 09](https://cloud.githubusercontent.com/assets/261579/12127791/26921b56-b3c7-11e5-859d-9419c0c389c4.png)
![screen shot 2016-01-05 at 16 12 04](https://cloud.githubusercontent.com/assets/261579/12127790/2691280e-b3c7-11e5-9c87-f0a08b6b34e5.png)

**Comment by lianghai** [comment]
Fixed in build 0.900.
